### ISSUE TITLE
Cozie for Fitbit Sense

### ISSUE THREAD

**Issue by AlexDonkers** [cozie-app/cozie#98]
Dear developers,

I'm performing PhD research in semantic digital twins (mainly for improving indoor environmental quality) and I'm currently working on integrating occupants and their active/passive feedback in the digital twin. It always struck me how much of a hassle it is for occupants to give simple feedback to a building’s operational state. I came across the amazing work you did in ‘Humans-as-a-Sensor for Buildings—Intensive Longitudinal Indoor Comfort Models’. I truly believe that apps like cozie can help to improve human feedback on buildings and enable more occupant-oriented system control in buildings. 

To truly understand the occupant, I'd like to capture as much comfort/health-related information and the Fitbit Sense seems to have a lot of health and stress sensors. However, based on your documentation, it appears that cozie only works for Ionic, Versa, Versa Lite, and Versa 2.

Would it be possible to update cozie to a Fitbit Sense app? How much time and expertise would that require?

Preferably, I'd like to create an app that can store both the medical sensors (stress, activity level, heart rate, SpO2) as well as active occupant feedback on the indoor environmental quality (including thermal comfort, air quality, visual comfort, and acoustic comfort). I'm happy to contribute to the project myself as well. 

Kind regards,
Alex

**Comment by cmiller8** [comment]
Thanks for the suggestion Alex! I have assigned @MahmoudAbdelRahman an I to this to this so we can make a timelime and investigate.

Do you have a timeline for when you need this?

**Comment by FedericoTartarini** [comment]
Hi Alex, I also would like to mention that we have also developed [Cozie for the Apple Watch](https://cozie-apple.app) which has some extra functionalities.

**Comment by AlexDonkers** [comment]
Hi guys, thanks for the replies. I went through the code of cozie and came to the conclusion that the product I need has some major differences/extensions from cozie. I chose to build something from scratch, as that's probably the fastest way. 

The app I'm building is a Versa 3/Sense app, so if you need some help with updating Cozie for Fitbit Versa 3/Sense, let me know!
